---
- name: Make Installation of Kops
  hosts: k8s_workstation
  become: true
  tasks:
    - name: Get kopsd version
      command: curl -s https://api.github.com/repos/kubernetes/kops/releases/latest 
      register: kops
    - debug: {var: kops.stdout}

    # - name: Install Kops binary
    #   command: |
    #     curl -Lo kops https://github.com/kubernetes/kops/releases/download/{{ kops.stdout }}/kops-linux-amd64

    # - name: Add permissions to Kops binary
    #   command: chmod +x kops
    
    # - name: Move Kops binary to /usr/local/bin
    #   command: mv kops /usr/local/bin/kops

    # - name: Validate Kops installation
    #   command: kops
    #   register: kops_version  
    # - debug: {var: kops_version.stdout}
