[deploy]
; app1 ansible_host=10.0.9.233 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/toche-key1 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
app1 ansible_host=10.0.12.239 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/toche-key1 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

; 10.0.12.239
